// flow-typed signature: f33fc95b4c676ee05a80b6510a9dc362
// flow-typed version: <<STUB>>/electron-log_v^3.0.4/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-log' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-log/lib/catchErrors' {
  declare module.exports: any;
}

declare module 'electron-log/lib/format' {
  declare module.exports: any;
}

declare module 'electron-log/lib/log' {
  declare module.exports: any;
}

declare module 'electron-log/lib/transports/console' {
  declare module.exports: any;
}

declare module 'electron-log/lib/transports/file/findLogPath' {
  declare module.exports: any;
}

declare module 'electron-log/lib/transports/file/getAppName' {
  declare module.exports: any;
}

declare module 'electron-log/lib/transports/file/index' {
  declare module.exports: any;
}

declare module 'electron-log/lib/transports/mainConsole' {
  declare module.exports: any;
}

declare module 'electron-log/lib/transports/remote' {
  declare module.exports: any;
}

declare module 'electron-log/lib/transports/rendererConsole' {
  declare module.exports: any;
}

declare module 'electron-log/lib/utils' {
  declare module.exports: any;
}

declare module 'electron-log/main' {
  declare module.exports: any;
}

declare module 'electron-log/renderer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-log/index' {
  declare module.exports: $Exports<'electron-log'>;
}
declare module 'electron-log/index.js' {
  declare module.exports: $Exports<'electron-log'>;
}
declare module 'electron-log/lib/catchErrors.js' {
  declare module.exports: $Exports<'electron-log/lib/catchErrors'>;
}
declare module 'electron-log/lib/format.js' {
  declare module.exports: $Exports<'electron-log/lib/format'>;
}
declare module 'electron-log/lib/log.js' {
  declare module.exports: $Exports<'electron-log/lib/log'>;
}
declare module 'electron-log/lib/transports/console.js' {
  declare module.exports: $Exports<'electron-log/lib/transports/console'>;
}
declare module 'electron-log/lib/transports/file/findLogPath.js' {
  declare module.exports: $Exports<'electron-log/lib/transports/file/findLogPath'>;
}
declare module 'electron-log/lib/transports/file/getAppName.js' {
  declare module.exports: $Exports<'electron-log/lib/transports/file/getAppName'>;
}
declare module 'electron-log/lib/transports/file/index.js' {
  declare module.exports: $Exports<'electron-log/lib/transports/file/index'>;
}
declare module 'electron-log/lib/transports/mainConsole.js' {
  declare module.exports: $Exports<'electron-log/lib/transports/mainConsole'>;
}
declare module 'electron-log/lib/transports/remote.js' {
  declare module.exports: $Exports<'electron-log/lib/transports/remote'>;
}
declare module 'electron-log/lib/transports/rendererConsole.js' {
  declare module.exports: $Exports<'electron-log/lib/transports/rendererConsole'>;
}
declare module 'electron-log/lib/utils.js' {
  declare module.exports: $Exports<'electron-log/lib/utils'>;
}
declare module 'electron-log/main.js' {
  declare module.exports: $Exports<'electron-log/main'>;
}
declare module 'electron-log/renderer.js' {
  declare module.exports: $Exports<'electron-log/renderer'>;
}
