// flow-typed signature: 1422cb720dc498ac5e44cdd2b91ff155
// flow-typed version: <<STUB>>/eslint-config-erb_v^0.0.2/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-erb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-erb' {
  declare module.exports: any;
}
