// flow-typed signature: 926187d33e5b1d29f21aa6e345a3223a
// flow-typed version: <<STUB>>/jsmpeg_v^1.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsmpeg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsmpeg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsmpeg/jsmpg' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsmpeg/jsmpg.js' {
  declare module.exports: $Exports<'jsmpeg/jsmpg'>;
}
