// flow-typed signature: 5efc015bb21a0dcfea3a5110f85385fe
// flow-typed version: <<STUB>>/nimble_v^0.0.2/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nimble'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nimble' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nimble/nimble' {
  declare module.exports: any;
}

declare module 'nimble/nimble.min' {
  declare module.exports: any;
}

declare module 'nimble/site/highlight.min' {
  declare module.exports: any;
}

declare module 'nimble/site/jquery-1.5.1.min' {
  declare module.exports: any;
}

declare module 'nimble/site/json2.min' {
  declare module.exports: any;
}

declare module 'nimble/test/JSLitmus' {
  declare module.exports: any;
}

declare module 'nimble/test/nodeunit' {
  declare module.exports: any;
}

declare module 'nimble/test/test_with_underscore' {
  declare module.exports: any;
}

declare module 'nimble/test/test' {
  declare module.exports: any;
}

declare module 'nimble/test/underscore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nimble/nimble.js' {
  declare module.exports: $Exports<'nimble/nimble'>;
}
declare module 'nimble/nimble.min.js' {
  declare module.exports: $Exports<'nimble/nimble.min'>;
}
declare module 'nimble/site/highlight.min.js' {
  declare module.exports: $Exports<'nimble/site/highlight.min'>;
}
declare module 'nimble/site/jquery-1.5.1.min.js' {
  declare module.exports: $Exports<'nimble/site/jquery-1.5.1.min'>;
}
declare module 'nimble/site/json2.min.js' {
  declare module.exports: $Exports<'nimble/site/json2.min'>;
}
declare module 'nimble/test/JSLitmus.js' {
  declare module.exports: $Exports<'nimble/test/JSLitmus'>;
}
declare module 'nimble/test/nodeunit.js' {
  declare module.exports: $Exports<'nimble/test/nodeunit'>;
}
declare module 'nimble/test/test_with_underscore.js' {
  declare module.exports: $Exports<'nimble/test/test_with_underscore'>;
}
declare module 'nimble/test/test.js' {
  declare module.exports: $Exports<'nimble/test/test'>;
}
declare module 'nimble/test/underscore.js' {
  declare module.exports: $Exports<'nimble/test/underscore'>;
}
