// flow-typed signature: c77a6230420b5536e85af155f193cd1f
// flow-typed version: <<STUB>>/node-rtsp-stream_v^0.0.8/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-rtsp-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-rtsp-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-rtsp-stream/mpeg1muxer' {
  declare module.exports: any;
}

declare module 'node-rtsp-stream/test' {
  declare module.exports: any;
}

declare module 'node-rtsp-stream/test/tests' {
  declare module.exports: any;
}

declare module 'node-rtsp-stream/videoStream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-rtsp-stream/index' {
  declare module.exports: $Exports<'node-rtsp-stream'>;
}
declare module 'node-rtsp-stream/index.js' {
  declare module.exports: $Exports<'node-rtsp-stream'>;
}
declare module 'node-rtsp-stream/mpeg1muxer.js' {
  declare module.exports: $Exports<'node-rtsp-stream/mpeg1muxer'>;
}
declare module 'node-rtsp-stream/test.js' {
  declare module.exports: $Exports<'node-rtsp-stream/test'>;
}
declare module 'node-rtsp-stream/test/tests.js' {
  declare module.exports: $Exports<'node-rtsp-stream/test/tests'>;
}
declare module 'node-rtsp-stream/videoStream.js' {
  declare module.exports: $Exports<'node-rtsp-stream/videoStream'>;
}
