// flow-typed signature: 450e0aba63dfb45fbc45f3f871d08c55
// flow-typed version: <<STUB>>/onvif_v^0.6.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'onvif'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'onvif' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'onvif/docs/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'onvif/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'onvif/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'onvif/example' {
  declare module.exports: any;
}

declare module 'onvif/example2' {
  declare module.exports: any;
}

declare module 'onvif/example3' {
  declare module.exports: any;
}

declare module 'onvif/example4' {
  declare module.exports: any;
}

declare module 'onvif/example5' {
  declare module.exports: any;
}

declare module 'onvif/lib/cam' {
  declare module.exports: any;
}

declare module 'onvif/lib/device' {
  declare module.exports: any;
}

declare module 'onvif/lib/discovery' {
  declare module.exports: any;
}

declare module 'onvif/lib/events' {
  declare module.exports: any;
}

declare module 'onvif/lib/imaging' {
  declare module.exports: any;
}

declare module 'onvif/lib/media' {
  declare module.exports: any;
}

declare module 'onvif/lib/onvif' {
  declare module.exports: any;
}

declare module 'onvif/lib/ptz' {
  declare module.exports: any;
}

declare module 'onvif/lib/recording' {
  declare module.exports: any;
}

declare module 'onvif/lib/replay' {
  declare module.exports: any;
}

declare module 'onvif/lib/utils' {
  declare module.exports: any;
}

declare module 'onvif/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'onvif/docs/scripts/linenumber.js' {
  declare module.exports: $Exports<'onvif/docs/scripts/linenumber'>;
}
declare module 'onvif/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'onvif/docs/scripts/prettify/lang-css'>;
}
declare module 'onvif/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'onvif/docs/scripts/prettify/prettify'>;
}
declare module 'onvif/example.js' {
  declare module.exports: $Exports<'onvif/example'>;
}
declare module 'onvif/example2.js' {
  declare module.exports: $Exports<'onvif/example2'>;
}
declare module 'onvif/example3.js' {
  declare module.exports: $Exports<'onvif/example3'>;
}
declare module 'onvif/example4.js' {
  declare module.exports: $Exports<'onvif/example4'>;
}
declare module 'onvif/example5.js' {
  declare module.exports: $Exports<'onvif/example5'>;
}
declare module 'onvif/lib/cam.js' {
  declare module.exports: $Exports<'onvif/lib/cam'>;
}
declare module 'onvif/lib/device.js' {
  declare module.exports: $Exports<'onvif/lib/device'>;
}
declare module 'onvif/lib/discovery.js' {
  declare module.exports: $Exports<'onvif/lib/discovery'>;
}
declare module 'onvif/lib/events.js' {
  declare module.exports: $Exports<'onvif/lib/events'>;
}
declare module 'onvif/lib/imaging.js' {
  declare module.exports: $Exports<'onvif/lib/imaging'>;
}
declare module 'onvif/lib/media.js' {
  declare module.exports: $Exports<'onvif/lib/media'>;
}
declare module 'onvif/lib/onvif.js' {
  declare module.exports: $Exports<'onvif/lib/onvif'>;
}
declare module 'onvif/lib/ptz.js' {
  declare module.exports: $Exports<'onvif/lib/ptz'>;
}
declare module 'onvif/lib/recording.js' {
  declare module.exports: $Exports<'onvif/lib/recording'>;
}
declare module 'onvif/lib/replay.js' {
  declare module.exports: $Exports<'onvif/lib/replay'>;
}
declare module 'onvif/lib/utils.js' {
  declare module.exports: $Exports<'onvif/lib/utils'>;
}
declare module 'onvif/test.js' {
  declare module.exports: $Exports<'onvif/test'>;
}
