// flow-typed signature: e3dd1a912b363561010528211a126948
// flow-typed version: <<STUB>>/python-shell_v^1.0.7/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'python-shell'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'python-shell' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'python-shell/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'python-shell/index' {
  declare module.exports: $Exports<'python-shell'>;
}
declare module 'python-shell/index.js' {
  declare module.exports: $Exports<'python-shell'>;
}
declare module 'python-shell/test.js' {
  declare module.exports: $Exports<'python-shell/test'>;
}
