// flow-typed signature: 9f79b269e1fe5fb2b07dd23efd794d57
// flow-typed version: <<STUB>>/react-native-navigation_v^3.0.0-alpha.3/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-navigation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-navigation/babel.config' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/adapters/AppRegistryService' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/adapters/AssetResolver' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/adapters/ColorService' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/adapters/Constants' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/adapters/NativeCommandsSender' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/adapters/NativeEventsReceiver' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/adapters/NativeEventsReceiver.mock' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/adapters/SharedElement' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/adapters/TouchablePreview' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/adapters/UniqueIdProvider' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/commands/Commands' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/commands/Commands.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/commands/LayoutTreeCrawler' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/commands/LayoutTreeCrawler.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/commands/LayoutTreeParser' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/commands/LayoutTreeParser.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/commands/LayoutType' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/commands/LayoutType.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/commands/OptionsProcessor' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/commands/OptionsProcessor.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/components/ComponentRegistry' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/components/ComponentRegistry.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/components/ComponentWrapper' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/components/ComponentWrapper.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/components/Store' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/components/Store.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/events/CommandsObserver' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/events/CommandsObserver.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/events/ComponentEventsObserver' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/events/ComponentEventsObserver.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/events/EventsRegistry' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/events/EventsRegistry.test' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/index' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/interfaces/ComponentEvents' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/interfaces/Events' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/interfaces/EventSubscription' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/interfaces/Layout' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/interfaces/Options' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/Navigation' {
  declare module.exports: any;
}

declare module 'react-native-navigation/lib/dist/types' {
  declare module.exports: any;
}

declare module 'react-native-navigation/metro.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-navigation/babel.config.js' {
  declare module.exports: $Exports<'react-native-navigation/babel.config'>;
}
declare module 'react-native-navigation/index' {
  declare module.exports: $Exports<'react-native-navigation'>;
}
declare module 'react-native-navigation/index.js' {
  declare module.exports: $Exports<'react-native-navigation'>;
}
declare module 'react-native-navigation/lib/dist/adapters/AppRegistryService.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/adapters/AppRegistryService'>;
}
declare module 'react-native-navigation/lib/dist/adapters/AssetResolver.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/adapters/AssetResolver'>;
}
declare module 'react-native-navigation/lib/dist/adapters/ColorService.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/adapters/ColorService'>;
}
declare module 'react-native-navigation/lib/dist/adapters/Constants.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/adapters/Constants'>;
}
declare module 'react-native-navigation/lib/dist/adapters/NativeCommandsSender.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/adapters/NativeCommandsSender'>;
}
declare module 'react-native-navigation/lib/dist/adapters/NativeEventsReceiver.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/adapters/NativeEventsReceiver'>;
}
declare module 'react-native-navigation/lib/dist/adapters/NativeEventsReceiver.mock.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/adapters/NativeEventsReceiver.mock'>;
}
declare module 'react-native-navigation/lib/dist/adapters/SharedElement.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/adapters/SharedElement'>;
}
declare module 'react-native-navigation/lib/dist/adapters/TouchablePreview.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/adapters/TouchablePreview'>;
}
declare module 'react-native-navigation/lib/dist/adapters/UniqueIdProvider.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/adapters/UniqueIdProvider'>;
}
declare module 'react-native-navigation/lib/dist/commands/Commands.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/commands/Commands'>;
}
declare module 'react-native-navigation/lib/dist/commands/Commands.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/commands/Commands.test'>;
}
declare module 'react-native-navigation/lib/dist/commands/LayoutTreeCrawler.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/commands/LayoutTreeCrawler'>;
}
declare module 'react-native-navigation/lib/dist/commands/LayoutTreeCrawler.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/commands/LayoutTreeCrawler.test'>;
}
declare module 'react-native-navigation/lib/dist/commands/LayoutTreeParser.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/commands/LayoutTreeParser'>;
}
declare module 'react-native-navigation/lib/dist/commands/LayoutTreeParser.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/commands/LayoutTreeParser.test'>;
}
declare module 'react-native-navigation/lib/dist/commands/LayoutType.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/commands/LayoutType'>;
}
declare module 'react-native-navigation/lib/dist/commands/LayoutType.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/commands/LayoutType.test'>;
}
declare module 'react-native-navigation/lib/dist/commands/OptionsProcessor.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/commands/OptionsProcessor'>;
}
declare module 'react-native-navigation/lib/dist/commands/OptionsProcessor.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/commands/OptionsProcessor.test'>;
}
declare module 'react-native-navigation/lib/dist/components/ComponentRegistry.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/components/ComponentRegistry'>;
}
declare module 'react-native-navigation/lib/dist/components/ComponentRegistry.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/components/ComponentRegistry.test'>;
}
declare module 'react-native-navigation/lib/dist/components/ComponentWrapper.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/components/ComponentWrapper'>;
}
declare module 'react-native-navigation/lib/dist/components/ComponentWrapper.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/components/ComponentWrapper.test'>;
}
declare module 'react-native-navigation/lib/dist/components/Store.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/components/Store'>;
}
declare module 'react-native-navigation/lib/dist/components/Store.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/components/Store.test'>;
}
declare module 'react-native-navigation/lib/dist/events/CommandsObserver.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/events/CommandsObserver'>;
}
declare module 'react-native-navigation/lib/dist/events/CommandsObserver.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/events/CommandsObserver.test'>;
}
declare module 'react-native-navigation/lib/dist/events/ComponentEventsObserver.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/events/ComponentEventsObserver'>;
}
declare module 'react-native-navigation/lib/dist/events/ComponentEventsObserver.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/events/ComponentEventsObserver.test'>;
}
declare module 'react-native-navigation/lib/dist/events/EventsRegistry.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/events/EventsRegistry'>;
}
declare module 'react-native-navigation/lib/dist/events/EventsRegistry.test.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/events/EventsRegistry.test'>;
}
declare module 'react-native-navigation/lib/dist/index.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/index'>;
}
declare module 'react-native-navigation/lib/dist/interfaces/ComponentEvents.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/interfaces/ComponentEvents'>;
}
declare module 'react-native-navigation/lib/dist/interfaces/Events.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/interfaces/Events'>;
}
declare module 'react-native-navigation/lib/dist/interfaces/EventSubscription.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/interfaces/EventSubscription'>;
}
declare module 'react-native-navigation/lib/dist/interfaces/Layout.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/interfaces/Layout'>;
}
declare module 'react-native-navigation/lib/dist/interfaces/Options.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/interfaces/Options'>;
}
declare module 'react-native-navigation/lib/dist/Navigation.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/Navigation'>;
}
declare module 'react-native-navigation/lib/dist/types.js' {
  declare module.exports: $Exports<'react-native-navigation/lib/dist/types'>;
}
declare module 'react-native-navigation/metro.config.js' {
  declare module.exports: $Exports<'react-native-navigation/metro.config'>;
}
