// flow-typed signature: dacec298964df7897fafc211972a8823
// flow-typed version: <<STUB>>/testcafe-react-selectors_v^3.1.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'testcafe-react-selectors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'testcafe-react-selectors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'testcafe-react-selectors/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'testcafe-react-selectors/lib/index.js' {
  declare module.exports: $Exports<'testcafe-react-selectors/lib/index'>;
}
