// flow-typed signature: f9ad7a01a8119f07a34f4239f2ce74df
// flow-typed version: <<STUB>>/@babel/plugin-transform-react-inline-elements_v^7.2.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-react-inline-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-react-inline-elements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-react-inline-elements/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-react-inline-elements/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-transform-react-inline-elements/lib/index'>;
}
